[package]
name = "pdfprint"
version = "0.1.0"
authors = ["Eugenio Tampieri <eugenio@eutampieri.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipp="3.0"
futures="0.3"
simple_logger = "1.11"
log="0.4"